#! /bin/bash

# Best Aliases
alias gst='git status'
alias b='bundle exec'
alias bcap='bundle exec cap'
alias brake='bundle exec rake'
alias brails='bundle exec rails'
alias bil='bundle install --path vendor/bundle'
alias up='git pull'
alias glo='git log'
alias autocop='bundle exec rake rubocop:lint_unpushed:auto_correct'
alias ms='bundle exec rake mysql'
alias msa='bundle exec rake mysql\[-A\]'
alias tdsd='td && sd'
alias dot=' cd ~/dev/dotfiles'
alias dock=' cd ~/dev/onyx_docker'
alias dup='docker-compose up -d'
alias ddown='docker-compose down'
alias ami=' cd ~/dev/ami-builder'
alias resettestdb="DATASET=sample_data SCHEMA=db/structure.sql RAILS_ENV=test bundle exec rails db:reset"
alias testserver="RAILS_ENV=test DISABLE_ONE_SEARCH_ASSET_LOAD=true SKIP_LOCAL_CACHE=true ENABLE_ALL_STUBS=true USE_MOCK_CACHE=false ENABLE_CACHER=true LOG_LEVEL=debug bundle exec rails server"
alias overspec="USE_MOCK_CACHE=false ENABLE_CACHER=true RAILS_ENV=test SAVE_FAILURE_SCREENSHOTS=true DISABLE_PROFILING=true bundle exec rspec -fd"
alias poosh="prepushhook"

# SHELL
alias ll='ls -lah'
alias reload='exec $SHELL -l'